[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#58A6FF"
backgroundColor = "#0F1117"
secondaryBackgroundColor = "#161B22"
textColor = "#F3F4F6"
font = "sans serif"
